---
resources:
  - name: pipelinetemplates
    type: git
    source:
      uri: ((templates_git_uri))
      branch: ((templates_git_branch))

  - name: app
    type: git
    source:
      uri: ((git_uri))
      branch: ((git_branch))

  - name: go-image
    type: registry-image
    source:
      repository: golang
      tag: ((go_version))

jobs:
  - name: build
    public: true
    plan:
      - get: app
        trigger: true
      - get: pipelinetemplates
        trigger: false
      - get: go-image
        trigger: false
      - task: build
        image: go-image
        file: pipelinetemplates/.concourse/go/go-build/tasks/build.yml
        vars:
          module_dir: ((module_dir))
          build_package: ((build_package))
          binary_name: ((binary_name))
          platforms: ((platforms))
          build_tags: ((build_tags))
          ldflags: ((ldflags))
          output_dir: ((output_dir))
