---
################################################################
# This pipeline creates versioned releases for the pipelines   #
# and workflows in this repository.                            #
#                                                              #
# The pipeline acccepts a pipeline reference and version, then #
# calls the release.sh script to bump that pipeline's version. #
#                                                              #
# This allows for pinning pipelines other repositories import  #
# from this repository to a specific version.                  #
################################################################

name: Tag specific pipeline

on:
  workflow_dispatch:
    inputs:
      template:
        description: Template key to release
        required: true
        type: string
      version:
        description: Version to release
        required: true
        type: string
      tag:
        description: Create a Git tag
        required: false
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update manifest and tag
        run: |
          chmod +x ./.scripts/release.sh

          if [[ "${{ inputs.tag }}" == "true" ]]; then
            ./.scripts/release.sh --template "${{ inputs.template }}" --version "${{ inputs.version }}" --tag
          else
            ./.scripts/release.sh --template "${{ inputs.template }}" --version "${{ inputs.version }}"
          fi

      - name: Push commit and tag
        run: |
          git push origin HEAD:main
          git push origin --tags
