---
#############################################################
# Placeholder publish pipeline for Go applications.         #
#                                                           #
# This currently prints artifact details only.              #
#############################################################

resources:
  - name: pipelinetemplates
    type: git
    source:
      uri: ((templates_git_uri))
      branch: ((templates_git_branch))

  - name: app
    type: git
    source:
      uri: ((git_uri))
      branch: ((git_branch))

  - name: go-image
    type: registry-image
    source:
      repository: golang
      tag: ((go_version))

jobs:
  - name: publish-go-app
    public: true
    plan:
      - get: pipelinetemplates
        trigger: true
      - get: app
        passed: [build-go-app]
        trigger: true
      - get: go-image

      - task: publish
        image: go-image
        file: pipelinetemplates/.concourse/go/go-build/tasks/publish.yml
        params:
          MODULE_DIR: ((module_dir))
          BINARY_NAME: ((binary_name))
          OUTPUT_DIR: ((output_dir))
