---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: renovate/renovate
    tag: latest

inputs:
  - name: app
  - name: pipelinetemplates

run:
  path: sh
  args:
    - -ec
    - |
      bash pipelinetemplates/.concourse/maint/renovate/scripts/renovate.sh
