---
platform: linux

inputs:
  - name: app
  - name: pipelinetemplates

outputs:
  - name: dist

run:
  path: /bin/bash
  args:
    - -euo
    - pipefail
    - pipelinetemplates/.concourse/go/go-build/scripts/build.sh

params:
  MODULE_DIR: ((module_dir))
  BUILD_PACKAGE: ((build_package))
  BINARY_NAME: ((binary_name))
  PLATFORMS: ((platforms))
  BUILD_TAGS: ((build_tags))
  LDFLAGS: ((ldflags))
  OUTPUT_DIR: ((output_dir))
