---
platform: linux
image: go-image

inputs:
  - name: app
  - name: pipelinetemplates
outputs:
  - name: output

params:
  MODULE_DIR:
  BUILD_PACKAGE:
  BINARY_NAME:
  PLATFORMS:
  BUILD_TAGS:
  LDFLAGS:
  OUTPUT_DIR:
  CGO_ENABLED:

run:
  path: sh
  args:
    - -ec
    - |
      chmod +x pipelinetemplates/.concourse/go/go-build/build.sh
      pipelinetemplates/.concourse/go/go-build/build.sh
