---
platform: linux
image: go-image

inputs:
  - name: app
  - name: pipelinetemplates
  - name: output

run:
  path: sh
  args:
    - -ec
    - |
      chmod +x pipelinetemplates/.concourse/go/go-build/scripts/publish.sh
      pipelinetemplates/.concourse/go/go-build/scripts/publish.sh