---
platform: linux

inputs:
  - name: app
  - name: pipelinetemplates
  - name: output

run:
  path: sh
  args:
    - -ec
    - |
      bash pipelinetemplates/.concourse/go/go-build/scripts/publish.sh
