---
platform: linux
image: go-image

inputs:
  - name: app
  - name: pipelinetemplates

run:
  path: sh
  args:
    - -ec
    - |
      chmod +x pipelinetemplates/.concourse/go/go-build/scripts/test.sh
      pipelinetemplates/.concourse/go/go-build/scripts/test.sh