---
######################################
# Deploy a Hugo site to Github Pages #
######################################

name: Hugo Publish GitHub Pages

on:
  workflow_call:
    inputs:
      run-id:
        description: "Build workflow run ID to download the artifact from."
        required: true
        type: string

      artifact-name:
        description: "Name of the build artifact to download."
        required: false
        type: string
        default: "hugo-site"

      dry-run:
        description: "If true, do not deploy."
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.artifact-name }}
          run-id: ${{ inputs.run-id }}
          github-token: ${{ github.token }}
          path: ./_published

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v6

      - name: Upload GitHub Pages artifact
        if: ${{ !inputs.dry-run }}
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./_published

      - name: Deploy to GitHub Pages
        if: ${{ !inputs.dry-run }}
        id: deployment
        uses: actions/deploy-pages@v5
