---
##########################################
# Send a notification to a Gotify server #
##########################################

name: Gotify Notification

on:
  workflow_call:
    inputs:
      gotify-url:
        description: "Base URL of the Gotify server"
        required: true
        type: string

      title:
        description: "Notification title"
        required: false
        type: string
        default: ""

      message:
        description: "Notification message"
        required: false
        type: string
        default: ""

      priority:
        description: "Gotify priority"
        required: false
        type: number
        default: 0

      use-json:
        description: "Use application/json payload instead of multipart form"
        required: false
        type: boolean
        default: true

      content-type:
        description: "Message rendering type"
        required: false
        type: string
        default: "text/plain"

      click-url:
        description: "URL to open when notification is clicked"
        required: false
        type: string
        default: ""

      big-image-url:
        description: "Large notification image"
        required: false
        type: string
        default: ""

      intent-url:
        description: "Android intent URL"
        required: false
        type: string
        default: ""

      extras-json:
        description: "Additional extras JSON merged into generated extras"
        required: false
        type: string
        default: "{}"

      raw-json-payload:
        description: "Completely override generated JSON payload"
        required: false
        type: string
        default: ""

      user-agent:
        description: "HTTP UA string to send with requests"
        required: false
        type: string
        default: "redjax/PipelineTemplates"

    secrets:
      gotify-token:
        required: true

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      ## Clone PipelineTemplates repo to dir named `pipelinetemplates/`,
      #  making scripts & other files in the PipelineTemplates repo available
      #  to the calling pipeline.
      - name: Checkout PipelineTemplates repo
        uses: actions/checkout@v6
        with:
          repository: redjax/PipelineTemplates
          ## `github.ref` uses the ref from the calling repo
          ref: ${{ github.ref }}
          path: pipelinetemplates

      - name: Send Gotify Notification
        shell: bash
        env:
          GOTIFY_URL: ${{ inputs.gotify-url }}
          GOTIFY_TOKEN: ${{ secrets.gotify-token }}
          TITLE: ${{ inputs.title }}
          MESSAGE: ${{ inputs.message }}
          PRIORITY: ${{ inputs.priority }}
          USE_JSON: ${{ inputs.use-json }}
          CONTENT_TYPE: ${{ inputs.content-type }}
          CLICK_URL: ${{ inputs.click-url }}
          BIG_IMAGE_URL: ${{ inputs.big-image-url }}
          INTENT_URL: ${{ inputs.intent-url }}
          USER_EXTRAS: ${{ inputs.extras-json }}
          RAW_JSON_PAYLOAD: ${{ inputs.raw-json-payload }}
          USER_AGENT: ${{ inputs.user-agent }}
          DEBUG: ${{ inputs.debug }}
        run: pipelinetemplates/shared/scripts/bash/gotify/send-notification.sh
