---
################################################
# Release changed components and publish tags. #
################################################

name: Publish components

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - run: git fetch origin main --force

      - name: Install deps
        run: ./shared/scripts/bash/installers/install-bump-my-version.sh

      - name: Release components
        env:
          PUSH: "true"
          COMMIT: "true"
        run: |
          ./shared/scripts/bash/versioning/release-components.sh

      - name: Tag components
        env:
          PUSH: "true"
        run: |
          ./shared/scripts/bash/versioning/git-tag-components.sh --push
